[package]
name = "gopsutil-rs"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
psutil = { version = "5.4.0", features = ["cpu", "disk", "host", "memory", "network", "process", "sensors"] }
